### PR TITLE
Graph1

### PR DESCRIPTION
**Pull request by ZoeRichter**
This pull should update the repo with the first draft of the diagrams for all reactors.  It includes changes from the 'graph' branch as well.

### CODE REVIEW

**Review by katyhuff — APPROVED** [review]
I am impressed! Thanks. I am definitely looking forward to some of the improvements you have in mind for the plots. (in open issues.)

**Comment by katyhuff** [comment]
@ZoeRichter which issues are closed by this merge?

**Comment by ZoeRichter** [comment]
I think issue7 should be able to be be closed, since the main goal was to get diagrams made in graphviz for use in SaltProc.  I would also say that these are the basic processing schemes, issue3, though I'd like to get opinions from the first round of reviews to make sure the diagrams are clear for people that aren't me.

**Comment by katyhuff** [comment]
@ZoeRichter Please close any issues that you believe should be closed.

**Pull request merged**
