### PR TITLE
First graphviz diagrams added

### PR DESCRIPTION
**Pull request by ZoeRichter**
This pull request contains a jupyter notebook that contains the first two graphs made with DOT language (MSRE and MSBR). 
Will be split into multiple pull requests because MSBR's processing scheme is complicated.

### CODE REVIEW

**Comment by andrewryh** [comment]
@ZoeRichter It covers just gas removal system?

**Comment by ZoeRichter** [comment]
Yes, I submitted this one with only two because the off gas system is more complicated.

**Review by andrewryh — CHANGES_REQUESTED** [review]
MSRE scheme doesn't contain any edges. I understand that it's probably obvious, but let's keep it formal. Edges (arrows) show the direction of material flow which is a big deal for SaltProc. That is my only comment.

**Comment by ZoeRichter** [comment]
For that one, the clustered nodes are part of the total fuel processing cell, and from what I understand, the portable absorber isn't a constant.  Should I just connect them in a line for now, so SaltProc can interpret it?

Also - how would SaltProc interpret a dummy, "empty" node?

**Comment by andrewryh** [comment]
> For that one, the clustered nodes are part of the total fuel processing cell, and from what I understand, the portable absorber isn't a constant. Should I just connect them in a line for now, so SaltProc can interpret it?
> 
> Also - how would SaltProc interpret a dummy, "empty" node?

I don't know yet because I didn't start code the parser. But most likely it will parse node data as parameters of Process class which is a single component of fuel reprocessing system.

Lines between node are material flows. It is a way to determine what is the order of Processes.

**Review by andrewryh — APPROVED** [review]
Looks good to me.

**Comment by andrewryh** [comment]
@ZoeRichter Some comment about the report: could you please add Li-7 enrichment for each reactor salt?  It might be helpful for model makers.

**Comment by ZoeRichter** [comment]
Will do!  Once this pull request has been merged, the one after this adds Li-7 enrichment.

**Pull request merged**
